version: "3.7"

services:
  pysonet-db:
    image: postgres:12
    volumes:
      - pysonet_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env.dev
    ports:
      - 5433:5433
    command: -p 5433

  pysonet_back:
    build: ./
    command: bash -c "python /usr/src/pysonet_app_dir/manage.py migrate --noinput && python /usr/src/pysonet_app_dir/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/pysonet_app_dir
    ports:
      - 8000:8000
    env_file:
      - ../.env.dev
    depends_on:
      - pysonet-db


volumes:
  pysonet_postgres_data:

